# basics

brew "stow"
brew "lsd"
brew "htop"
brew "btop"
brew "git"
brew "tree"
brew "wget"
brew "curl"

# infosec

brew "netcat"
brew "nmap"
brew "gnupg"

# javascript

brew "node"

# GenAI

brew "ollama"

# python

brew "pyenv"
brew "python@3.14"
cask "pycharm"

# rust

brew "rust"

# virtualization

brew "qemu"
cask "virtualbox"

# terminal

cask "iterm2"
brew "starship"
cask "font-fira-code"
cask "font-jetbrains-mono-nerd-font"

# apps

cask "google-chrome"
cask "audacity"
cask "calibre"
cask "firefox"
cask "libreoffice"
cask "steam"
cask "transmission"

# downloads

brew "get_iplayer"
brew "yt-dlp"

# IDEs

cask "intellij-idea-ce"

# text editors

cask "visual-studio-code"

# vscode plugins

vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "rust-lang.rust-analyzer"
vscode "tamasfe.even-better-toml"
vscode "zhuangtongfa.material-theme"
