# basics

brew "stow"
brew "lsd"
brew "htop"
brew "btop"
brew "git"
brew "tree"
brew "wget"
brew "curl"
brew "fastfetch"

# nvim and dependencies

brew "nvim"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "ast-grep"
brew "luarocks"

# infosec

brew "nmap"
brew "gnupg"
brew "pinentry-mac"
brew "gpgme"
cask "gpg-suite-no-mail"
cask "mitmproxy"
cask "proton-mail"
cask "proton-drive"
cask "protonvpn"

# autoreconf -> ./configure -> make -> make install

brew "autogen"
brew "automake"
brew "gnutls"
brew "readline"
brew "texinfo"

# api clients

cask "bruno"
cask "postman"

# javascript

brew "node"
brew "jq"

# GenAI

cask "ollama-app"
tap "anomalyco/tap"
brew "anomalyco/tap/opencode"

# python

brew "pyenv"
brew "python@3.14"
cask "pycharm"

# rust

brew "rust"

# go

brew "go"

# virtualization

brew "qemu"
cask "virtualbox"

# terminal

cask "ghostty"
brew "starship"
cask "font-fira-code"
cask "font-jetbrains-mono-nerd-font"

# apps

cask "audacity"
cask "calibre"
cask "libreoffice"
cask "steam"
cask "transmission"

# browsers

cask "duckduckgo"
cask "google-chrome"
cask "firefox"

# downloads

brew "get_iplayer"
brew "yt-dlp"

# IDEs

cask "intellij-idea-ce"

# xcode

brew "xcodegen"

# text editors

cask "visual-studio-code"

# vscode plugins

vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "rust-lang.rust-analyzer"
vscode "tamasfe.even-better-toml"
vscode "zhuangtongfa.material-theme"
vscode "yzhang.markdown-all-in-one"
vscode "ms-vscode.cpptools-extension-pack"
